# Generated by Django 6.0.1 on 2026-01-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead'), ('new_visit', 'New Visit'), ('followup_due', 'Follow-up Due'), ('lead_status_change', 'Lead Status Change'), ('visit_reminder', 'Visit Reminder'), ('system', 'System'), ('info', 'Information')], default='info', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'bell', 'check', 'warning')", max_length=50)),
                ('link', models.CharField(blank=True, help_text='Optional link to related page', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='If null, notification is for all users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='crm_systemn_user_id_bd5546_idx'), models.Index(fields=['user', 'is_read'], name='crm_systemn_user_id_59f844_idx')],
            },
        ),
    ]
